# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0002_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
