# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0003_auto_20160219_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
