# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0006_auto_20160226_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=160)),
                ('post_date', models.DateTimeField(verbose_name='date made')),
                ('post_author', models.CharField(max_length=40)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.Post')),
            ],
        ),
    ]
